export enum UPDATE_STATUS {
    ERROR = -1,
    START = 0,
    HAS_NEW_VERSION = 1,
    HAS_NOT_NEW_VERSION = 2,
    DOWNLOAD_PROGRESS = 3,
    DOWNLOAD_SUCCESS = 4,
}

export enum UPDATE_SIGNAL {
    CHECK_UPDATE = 'CHECK_UPDATE',
    CONFIRM_UPDATE = 'CONFIRM_UPDATE',
    UPDATE_MSG = 'UPDATE_MSG',
}